# Generated by Django 5.2.10 on 2026-01-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstateAggregator', '0002_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
