# Generated by Django 5.2.10 on 2026-01-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstateAggregator', '0003_alter_property_address_alter_property_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
