# Generated by Django 5.2.10 on 2026-02-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstateAggregator', '0004_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(default='USD', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='object_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(
                fields=['price'], 
                name='realEstateA_price_11fc00_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(
                fields=['address'], 
                name='realEstateA_address_513ffe_idx'
            ),
        ),
    ]
