# Generated by Django 5.2.10 on 2026-01-27 11:51

import re

from django.db import migrations


def fill_object_id(apps, schema_editor):
    Property = apps.get_model('realEstateAggregator', 'Property')
    for property in Property.objects.all():
        match = re.search(r'/(\d+)-[^/]+/?$', property.url)
        if match:
            property.object_id = int(match.group(1))
            property.save(update_fields=['object_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('realEstateAggregator', '0005_property_currency_property_object_id_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_object_id),
    ]
