# Generated by Django 5.2.10 on 2026-02-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstateAggregator', '0006_fill_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='object_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='url',
            field=models.URLField(),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(
                fields=('object_id',), 
                name='unique_property_object_id'
            ),
        ),
    ]
