# Generated by Django 5.2.10 on 2026-02-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstateAggregator', '0007_alter_property_object_id_alter_property_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
